# Generated by Django 3.2.6 on 2021-08-20 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_song_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='song',
            name='year',
            field=models.PositiveIntegerField(help_text='Use the following format: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
