# Generated by Django 3.2.4 on 2021-08-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210821_2109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewplaylist',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='reviewsong',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='song',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
