# Generated by Django 3.2.4 on 2021-08-23 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_song_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewplaylist',
            name='rating',
            field=models.PositiveIntegerField(help_text='Leave a rating up to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reviewsong',
            name='rating',
            field=models.PositiveIntegerField(help_text='Leave a rating up to 5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
