# Generated by Django 3.2.4 on 2021-08-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210823_2040'),
        ('main_app', '0005_auto_20210823_2250'),
    ]

    operations = [
    ]
