# Generated by Django 3.2.4 on 2021-08-23 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210823_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewplaylist',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.playlist'),
        ),
    ]
